apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox
  # annotations:
  #   # Reloading restricted by annotated deployments
  #   reloader.stakater.com/match: "true"
data:
  test.json: |-
    {
      "additional": "new",
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      }
    }
