apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
  annotations:
    # ALL ConfigMaps and Secrets used in this deployment
    reloader.stakater.com/auto: "true"
    # only ConfigMaps and Secrets used in this deployment and annotated with 'reloader.stakater.com/match: "true"'
    # reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: pause
          image: k8s.gcr.io/pause
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: kubectl
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          volumeMounts:
            - name: config
              mountPath: /opt/bitnami/test.json
              subPath: test.json
      volumes:
        - name: config
          configMap:
            name: kubectl
