apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
spec:
  replicas: 1
  # revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
  template:
    metadata:
      labels:
        app: reloader
    spec:
      serviceAccountName: reloader
      containers:
        - name: reloader
          image: stakater/reloader:v0.0.74
          imagePullPolicy: IfNotPresent
          # args:
          #   - --log-format=json
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - name: http
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
